<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <ENGINE_RESOURCE_INC>$(SolutionDir)EngineResource</ENGINE_RESOURCE_INC>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(ENGINE_RESOURCE_INC);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(TargetDir);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>EngineResource.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command></Command>
    </PostBuildEvent>    
    <PreBuildEvent>
    </PreBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="ENGINE_RESOURCE_INC">
      <Value>$(ENGINE_RESOURCE_INC)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>