<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)thirdparty\install\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SolutionDir)thirdparty\install\$(Configuration)\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>slang.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>    
    <PreBuildEvent>
      <Command>copy /Y $(SolutionDir)thirdparty\install\$(Configuration)\bin\slang.dll $(OutDir) </Command>
    </PreBuildEvent>
    <PostBuildEvent>
      <Command></Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
</Project>