<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <VMA_DIR>$(SolutionDir)thirdparty\install_VulkanMemoryAllocator</VMA_DIR>
    <VMA_INC>$(VMA_DIR)\include</VMA_INC>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(VMA_INC);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <PostBuildEvent>
      <Command></Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="VMA_DIR">
      <Value>$(VMA_DIR)</Value>
    </BuildMacro>
    <BuildMacro Include="VMA_INC">
      <Value>$(VMA_INC)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>